<?php
return array(
  'actionbox_contact_list' => '/actbox_contact_list.php',
  'actionbox_contact_status' => '/actbox_contact_status.php',
  'actionbox_login' => '/actbox_login.php',
  'actionbox_login_handle' => '/actbox_login_handle.php',
  'actionbox_richtext_surfer' => '/actbox_richtext_surfer.php',
  'actionbox_surfers_online' => '/actbox_surfers_online.php',
  'actionbox_topic_tag_surfers' => '/actbox_topic_tag_surfers.php',
  'alias_surferhandle' => '/alias_surferhandle.php',
  'contact_manager' => '/base_contacts.php',
  'surfer_admin' => '/base_surfers.php',
  'surfer_admin_edit' => '/base_surfers_edit.php',
  'connector_surfers' => '/connector_surfers.php',
  'connector_surfers_legacy' => '/connector_surfers_legacy.php',
  'content_avatarupload' => '/content_avatarupload.php',
  'content_contact' => '/content_contact.php',
  'content_contact_list' => '/content_contact_list.php',
  'content_login' => '/content_login.php',
  'content_profile' => '/content_profile.php',
  'content_profile_change_confirmation' => '/content_profile_change_confirmation.php',
  'content_register' => '/content_register.php',
  'content_showuser' => '/content_showuser.php',
  'content_showuser_list' => '/content_showuser_list.php',
  'convert_community' => '/convert_community.php',
  'cronjob_clear_contactcache' => '/cronjob_clear_contactcache.php',
  'cronjob_clear_oldrequests' => '/cronjob_clear_oldrequests.php',
  'edmodule_community' => '/edmodule_community.php'
);
